import"./assets/styles-Dt4zwTEg.js";import{i,a}from"./assets/vendor-4yCzdkXl.js";function k(t,o,n){t.forEach(s=>s.classList.remove(n)),o.classList.add(n)}function $(t,o="success"){const n={message:t,position:"topRight",timeout:3e3};switch(o){case"success":i.success(n);break;case"error":i.error(n);break;case"warning":i.warning(n);break;case"info":i.info(n);break;default:i.error({message:"invalid type of toast",position:"topRight",timeout:3e3})}}const c={categoriesList:document.querySelector(".categories"),productList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),modalProduct:document.querySelector(".modal-product"),searchForm:document.querySelector(".search-form"),searchFormClearBtn:document.querySelector(".search-form__btn-clear"),addToCartBtn:document.querySelector(".modal-product__btn--cart")};function R(){c.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",document.addEventListener("keydown",S),c.modalCloseBtn.addEventListener("click",b),c.modal.addEventListener("click",v)}function f(){c.modal.classList.remove("modal--is-open"),document.body.style.overflow="",document.removeEventListener("keydown",S),c.modalCloseBtn.removeEventListener("click",b),c.modal.removeEventListener("click",v)}function S(t){t.code==="Escape"&&f()}function b(){f()}function v(t){t.target===c.modal&&f()}const A="https://dummyjson.com",d={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_CATEGORY:"/products/category/",PRODUCT_BY_ID:"/products/",PRODUCT_BY_SEARCH:"/products/search"},I={CART:"cart",WHISHLIST:"whishlist",THEME:"theme"};a.defaults.baseURL=A;function O(){return a.get(d.CATEGORIES).then(({data:t})=>t)}function C(){return a.get(d.PRODUCTS).then(({data:t})=>t.products)}function D(t){return a.get(`${d.PRODUCTS_BY_CATEGORY}${t}`).then(({data:o})=>o)}function q(t){return a.get(`${d.PRODUCT_BY_ID}${t}`).then(({data:o})=>o)}function w(t){return a.get(`${d.PRODUCT_BY_SEARCH}?q=${t}`).then(({data:o})=>o)}function F(t){const n=["All",...t].map(r=>`<li class="categories__item">
   <button class="categories__btn" type="button">${r}</button>
 </li>`).join("");c.categoriesList.innerHTML=n;const s=document.querySelector(".categories__btn");s&&s.classList.add("categories__btn--active")}function l(t){const o=t.map(({id:n,thumbnail:s,title:r,brand:p,category:g,price:_})=>`<li class="products__item" data-id="${n}">
    <img class="products__image" src="${s}" alt="${r}"/>
    <p class="products__title">${r}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${p}</span></p>
    <p class="products__category">Category:${g} </p>
    <p class="products__price">Price:${_} $</p>
 </li>`).join("");c.productList.insertAdjacentHTML("beforeend",o)}function H({id:t,thumbnail:o,title:n,brand:s,category:r,price:p,description:g,shippingInformation:_,returnPolicy:E,tags:L}){const P=L?L.map(B=>`<li class="modal-product__tag" > ${B}</li>`).join(""):"",T=`<img class="modal-product__img" src="${o}" alt="${n}" />

<div class="modal-product__content"> <p class="modal-product__title">${n}</p>
<ul class="modal-product__tags">${P}</ul> <p class="modal-product__description">${g}</p>
<p class="modal-product__shipping-information">Shipping: ${_}</p>
<p class="modal-product__return-policy">Return Policy: ${E}</p>
<p class="modal-product__price">Price: ${p}$</p>
<button class="modal-product__buy-btn" type="button">Buy</button> </div>
`;c.modalProduct.innerHTML=T}function u(){c.notFound.classList.remove("not-found--visible")}function m(){c.notFound.classList.add("not-found--visible")}function y(){c.productList.innerHTML=""}function M(t){try{const o=localStorage.getItem(t);return o?JSON.parse(o):null}catch(o){return console.log(o.message),null}}function U(){return M(I.CART)??[]}function Y(t){return U().includes(t)}let h=null;function N(){O().then(t=>F(t)).catch(t=>{console.log("помидка запиту сторінки Home",t)}),C().then(t=>{l(t)}).catch(t=>{console.log("помилка рендеру продуктів",t)})}function j(t){const o=document.querySelectorAll(".categories__btn"),n=t.target.closest(".categories__btn");if(!n)return;y(),k(o,n,"categories__btn--active");const s=n.textContent.trim();s==="All"?C().then(r=>{l(r),u()}).catch(r=>{console.log("помилка рендеру продуктів",r)}):D(s).then(({products:r})=>{r.length>0?(l(r),u()):m()}).catch(r=>{console.log("помилка рендеру продуктів",r),m()})}function G(t){const o=t.target.closest(".products__item");if(!o)return;const n=Number(o.dataset.id);h=n,q(n).then(s=>{R(),H(s)})}function V(t){t.preventDefault();const o=t.target.elements.searchValue.value.trim();if(!o){$("Please enter valid search query","warning");return}w(o).then(({products:n})=>{y(),n.length>0?(l(n),u()):m()}).catch(n=>{console.log(n),m()})}function W(t){c.searchForm.reset(),y(),C().then(({products:o})=>{l(o),u()}).catch(o=>console.log("Error on handleSearchClear"),e)}function x(t){h&&Y(h)}document.addEventListener("DOMContentLoaded",N);c.categoriesList.addEventListener("click",j);c.productList.addEventListener("click",G);c.searchForm.addEventListener("submit",V);c.searchFormClearBtn.addEventListener("click",W);c.addToCartBtn.addEventListener("click",x);
//# sourceMappingURL=index.js.map
